apiVersion: v1
kind: ConfigMap
metadata: 
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    tier: backend
    component: cart
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      env: dev
      tier: backend
      component: cart
  template:
    metadata:
      name: cart
      labels:
        project: roboshop
        env: dev
        tier: backend
        component: cart
    spec:
      containers:
      - name: cart
        image: someshwarsangaraju/cart:v1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          failureThreshold: 1
          periodSeconds: 10
        resources:
          requests:
            memory: "1200mi"
            cpu: "500m"
          limits:
            memory: "1400mi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    tier: backend
    component: cart
  ports:
  - protocol: "TCP"
    port: "8080"
    targetPort: "8080"

