apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    tier: backend
    component: shipping
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      env: dev
      tier: backend
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        tier: backend
        component: shipping
    spec:
      containers:
      - name: shipping
        image: someshwarsangaraju/shipping:v1
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        # resources:
        #   requests:
        #     cpu: "1000m"
        #     memory: "1200mi"
        #   limits:
        #     cpu: "1000m"
        #     memory: "1400mi"
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

