apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    tier: database
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      tier: database
      component: mysql
  template:
    metadata:
      name: mysql
      labels:
        project: roboshop
        env: dev
        tier: database
        component: mysql
    spec:
      containers:
      - name: mysql
        image: someshwarsangaraju/mysql:v1
        imagePullPolicy: ALways
        # readinessProbe:
        #   tcpSocket: 
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
        # livelinessProbe:
        #   tcpSocket: 
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "200mi"
          limits:
            cpu: "400m"
            memory: "400mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    tier: database
    component: mysql
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
          
    
