apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels: 
    project: roboshop
    env: dev
    tier: database
    component: rabbitmq
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      tier: database
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        project: roboshop
        env: dev
        tier: database
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 5672
            path: /health
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            port: 5672
            path: /health
          failureThreshold: 1
          periodSeconds: 20
        resources:
          request:
            memory: "1100mi"
            cpu: "1200m"
          limits:
            memory: "1200mi"
            cpu: "1400m"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec: 
  selector:
    project: roboshop
    env: dev
    tier: database
    component: rabbitmq
  ports:
  - protocol: "TCP"
    port: "5672"
    targetPort: "5672"