apiVersion: v1
kind: ConfigMap
metadata: 
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    tier: backend
    component: payment
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      env: dev
      tier: backend
      component: payment
  template:
    metadata:
      name: payment
      labels:
        project: roboshop
        env: dev
        tier: backend
        component: payment
    spec:
      containers:
      - name: payment
        image: someshwarsangaraju/payment:v1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          failureThreshold: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          failureThreshold: 1
          periodSeconds: 10
        # resources:
        #   requests:
        #     cpu: "1200m"
        #     memory: "1200mi"
        #   limits:
        #     cpu: "1300m"
        #     memory: "1400mi"
        envFrom:
        - configMapRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    tier: backend
    component: payment
  ports:
  - protocol: "TCP"
    port: "8080"
    targetPort: "8080"

