apiVersion: v1
kind: Pod
metadata:
  name: errors-test
  labels:
    project: roboshop
    environment: dev
    purpose: errors-test
spec:
  containers:
  # - name: nginx
  #   image: nginx
  - name: almalinux
    image: almalinux:9
