apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations: 
    imageregistry: "https://hub.docker.com/"
  labels:
    project: roboshop
    environment: dev
    purpose: annotations
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "64m"
        memory: "100mi"  
      limits:
        cpu: "400m"
        memory: "550mi"