apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    project: roboshop
    environment: dev
    purpose: podlimits
spec: 
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "100mi"
        cpu: "125m"
      limits:
        memory: "150mi"
        cpu: "200m"
