apiVersion: v1
kind: Pod
metadata: 
  name: environment
  labels:
    project: roboshop
    environment: dev
    purpose: env
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "100mi"
        cpu: "250m"
      limits:
        memory: "200mi"
        cpu: "500m"
    env:
    - name: "nginx"
      value: "image"