apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
  labels:
    project: roboshop
    environment: dev
    purpose: secrets
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      request: 
        memory: "100mi"
        cpu: "100m"
      limits:
        memory: "200mi"
        cpu: "200mi"
    envFrom:
    - secretRef:
        name: pod-secrets