apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
spec:
  selector:
    project: roboshop
    environment: dev
    purpose: nodeport
  type: NodePort
  ports:
  - protocol: "TCP"
    port: "80"
    targetPort: "8080"
    nodePort: 30007
